version: '3.7'

services:
  influxdb-export:
    image: revenberg/influxdb-export:latest
    container_name: influxdb-export
    restart: always
    ports:
      - 9001:9001
    expose:
      - 9001
    volumes:
      # Data persistency
      # sudo mkdir -p /var/docker-compose/data/influxdb-export
      #- /var/docker-compose/data/influxdb-export/data/backup:/data/backup
    environment:
      - LOG_LEVEL=DEBUG
      - MQTT_ADDRESS=192.168.2.71
      - MQTT_TOPIC=reading/#
      - INFLUXDB_ADDRESS=192.168.2.71
      - INFLUXDB_PORT=8086
